# Generated by Django 2.1.5 on 2019-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ending_time',
            field=models.IntegerField(default=666),
        ),
        migrations.AddField(
            model_name='customer',
            name='starting_time',
            field=models.IntegerField(default=666),
        ),
    ]
