# Generated by Django 2.1.5 on 2019-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190311_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('timeslot', models.CharField(max_length=50)),
                ('worktime', models.IntegerField(default=666)),
            ],
        ),
    ]
