# Generated by Django 2.1.5 on 2019-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='timeslot',
            field=models.CharField(default='', max_length=50),
        ),
    ]
