# Generated by Django 2.1.5 on 2019-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working',
            field=models.IntegerField(default=1),
        ),
    ]
