# Generated by Django 2.1.5 on 2019-03-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_employee_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
