# Generated by Django 2.1.5 on 2019-03-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
